---
title: "Public Safety"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
date: "`r Sys.Date()`"    
---

<style>                     
.navbar {
  background-color:#46b5d2;
  border-color:black;
}
.navbar-brand {
font-weight: bold;
}
</style> 


```{r  message=FALSE, warning=FALSE, cache = TRUE}
library(flexdashboard)
library(plyr)
library(tidyverse)
library(lubridate)
library(ggpubr)
library(plotly)
theme_set(theme_pubr())
#////////////////////////////////////////////////
## Load All Police Runs Files from CovData Site /
#////////////////////////////////////////////////

##Store police file ids in vector
#file for 2013-most current year
p_file_ids <- c("0BxZjyP_Xfv7cbEVjbUNQV2k3WTA", "0BxZjyP_Xfv7cNzRqSzl3aS0wQjg", "0BxZjyP_Xfv7ccnk4N2EyZWVhd2c",
              "0BxZjyP_Xfv7cci1hdzBaTVRiTkk", "0BxZjyP_Xfv7cM1pselEtbUVmRTg", "10Ppmi-L4r84_-2hU9TqsLDhVWogymQUz",
              "1fDmpOwOwnm6wbCSQtwQlywK7QeDJn2Ql", "1X4Wf7_FaVwszCxetjSPPq8TWCMfG-2GA", "1mS-tptRDvfwrg5XOIilQqp1nMJDzyv4-",
              "1CTIqcChCexp-iITeHCiT3eT7utIN2Sty") 

#Paste file ids and download string and store in list
dwnld_p_file_ids <- lapply(p_file_ids, function(x) paste0("https://drive.google.com/uc?export=download&id=", x, 
                                                      collapse = ""))

#Read content of each file into a list
pruns_files <- lapply(dwnld_p_file_ids, function(x) read.csv(file = x))

#Bind list of files into a data frame
pruns <- rbind.fill(pruns_files)

#Incident Types for police run graphics
report_categories <- c("Shooting / Gunshot Wound", "Drug Activity", "Drunk Driver / DUI",
                       "Burglary", "Robbery")

#Not Covington Runs
not_cov_runs <- c("Mutual Aid")

#Final data frame for police data graphics
#Keeping last five years
pruns_report <- pruns %>%
  mutate(YMD = format(strptime(Date_Time, format='%Y-%m-%d %H:%M:%S'), '%Y-%m-%d'),
         FY.Q = quarter(YMD, with_year = TRUE, fiscal_start = 7),
         Qrt = paste("Q", quarter(YMD, with_year = FALSE, fiscal_start = 7), sep = ""))%>%
  filter(Incident_Type %in% report_categories & 
         FY.Q >= 2018.1 &
         !(Neighborhood %in% not_cov_runs))%>%
  select(c(3, 11, 12))%>%
  mutate(across(everything(), as.character),
        FY = str_sub(FY.Q, 1, 4),
        Qrt = factor(Qrt, levels = c("Q4", "Q3", "Q2", "Q1")))
      
 
#//////////////////////////////////////////////
## Load All Fire Runs Files from CovData Site /
#//////////////////////////////////////////////

##Store fire file ids in vector
#file for 2014-most current year
f_file_ids <- c("0BxZjyP_Xfv7cZWUzc0VaWTdrOTA", "0BxZjyP_Xfv7cVXAycExjNldxQU0", "0BxZjyP_Xfv7ccEtOMEU4RTRQclE",
              "0BxZjyP_Xfv7cNEQ0UlVNWVlIdUU", "1ywuDOr6X0vSSikRCkm6Yap5FiKESZ_ge", "1QuHl2AylMJiWj3kzV09KOMTTmIb5PxQL",
              "1ucdF5frigRk6CstDmCNa3_QyR4mCErQe", "11G72bCYPeN7umdzNlTt4I5F8-84146Yt", "1CVUedEypK3BrD6hg3nHq0X2aB-LkSzbO") 

#Paste file ids and download string and store in list
dwnld_f_file_ids <- lapply(f_file_ids, function(x) paste0("https://drive.google.com/uc?export=download&id=", x, 
                                                      collapse = ""))

#Read content of each file into a list
fruns_files <- lapply(dwnld_f_file_ids, function(x) read.csv(file = x))

#Bind list of files into a data frame
fruns <- rbind.fill(fruns_files)

#Incident Types for structure fire graphics
fire_categories <- c("Structure Fire")

#Not Covington Runs
not_cov_runs <- c("Mutual Aid")


#Final data frame for fire data graphics
#Keeping last five years
fruns_report <- fruns %>%
  mutate(YMD = ymd(Date),
         FY.Q = quarter(YMD, with_year = TRUE, fiscal_start = 7),
         Qrt = paste("Q", quarter(YMD, with_year = FALSE, fiscal_start = 7), sep = ""))%>%
  filter(Incident_Description %in% fire_categories & 
         FY.Q >= 2018.1 &
         !(Neighborhood %in% not_cov_runs))%>%
  select(c(4, 12, 13))%>%
  mutate(across(everything(), as.character),
        FY = str_sub(FY.Q, 1, 4),
        Qrt = factor(Qrt, levels = c("Q4", "Q3", "Q2", "Q1")))

```

Row 
-----------------------------------------------------------------------

### Reported Shootings
```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

## Keep reported shootings
shootings <- pruns_report %>%
  filter(Incident_Type == report_categories[1])

#Making plot
shootings_plot <- shootings %>%
  mutate(Count = 1)%>%
  group_by(FY, Qrt)%>%
  summarise(Shootings = sum(Count))%>%
  ggplot(aes(x=FY, y=Shootings, fill = Qrt))+
  geom_bar(stat = 'identity')+
  #scale_fill_manual(values=c('#999999','#E69F00'))+
  geom_text(aes(label=Shootings),  position= position_stack(0.5), size = 2.4)+
  theme_bw()+
  theme(legend.position = "top",
        legend.title = element_blank(),
        axis.text.x = element_text(size = 8),
        axis.title = element_blank())

#Interactive plot
ggplotly(shootings_plot)%>%
  layout(legend = list(
    orientation = "v"))
```



### Drug Activity Responses
```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}


## Keep reported drug activity
drug_activity <- pruns_report %>%
  filter(Incident_Type == report_categories[2])

#Making plot
drugs_plot <- drug_activity %>%
  mutate(Count = 1)%>%
  group_by(FY, Qrt)%>%
  summarise(Drug_Activity = sum(Count))%>%
  ggplot(aes(x=FY, y=Drug_Activity, fill = Qrt))+
  geom_bar(stat = 'identity')+
  #scale_fill_manual(values=c('#999999','#E69F00'))+
  geom_text(aes(label=Drug_Activity),  position= position_stack(0.5), size = 2.4)+
  theme_bw()+
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(size = 8),
        axis.title = element_blank())

#Interactive plot
ggplotly(drugs_plot)%>%
  layout(legend = list(
    orientation = "v"))
```




### Drunk Driver / DUI
```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

## Keep drunk driver / dui runs
dui <- pruns_report %>%
  filter(Incident_Type == report_categories[3])

#Making plot
dui_plot <- dui %>%
  mutate(Count = 1)%>%
  group_by(FY, Qrt)%>%
  summarise(DUIs = sum(Count))%>%
  ggplot(aes(x=FY, y=DUIs, fill = Qrt))+
  geom_bar(stat = 'identity')+
  #scale_fill_manual(values=c('#999999','#E69F00'))+
  geom_text(aes(label=DUIs),  position= position_stack(0.5), size = 2.4)+
  theme_bw()+
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(size = 8),
        axis.title = element_blank())

#Interactive plot
ggplotly(dui_plot)%>%
  layout(legend = list(
    orientation = "v"))
```

Row
-----------------------------------------------------------------------

### Structure Fires
```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

#Making plot
fires_plot <- fruns_report %>%
  mutate(Count = 1)%>%
  group_by(FY, Qrt)%>%
  summarise(Str_Fires = sum(Count))%>%
  ggplot(aes(x=FY, y=Str_Fires, fill = Qrt))+
  geom_bar(stat = 'identity')+
  #scale_fill_manual(values=c('#999999','#E69F00'))+
  geom_text(aes(label=Str_Fires),  position= position_stack(0.5), size = 2.4)+
  theme_bw()+
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(size = 8),
        axis.title = element_blank())

#Interactive plot
ggplotly(fires_plot)%>%
  layout(legend = list(orientation = "v"))

```

### Reported Burglaries
```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

## Keep reported drug activity
burglaries <- pruns_report %>%
  filter(Incident_Type == report_categories[4])

#Making plot
burglary_plot <- burglaries %>%
  mutate(Count = 1)%>%
  group_by(FY, Qrt)%>%
  summarise(Burglaries = sum(Count))%>%
  ggplot(aes(x=FY, y=Burglaries, fill = Qrt))+
  geom_bar(stat = 'identity')+
  #scale_fill_manual(values=c('#999999','#E69F00'))+
  geom_text(aes(label=Burglaries),  position= position_stack(0.5), size = 2.4)+
  theme_bw()+
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(size = 8),
        axis.title = element_blank())

#Interactive plot
ggplotly(burglary_plot)%>%
  layout(legend = list(
    orientation = "v"))

```
### Reported Robberies
```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

## Keep reported drug activity
robberies <- pruns_report %>%
  filter(Incident_Type == report_categories[5])

#Making plot
robbery_plot <- robberies %>%
  mutate(Count = 1)%>%
  group_by(FY, Qrt)%>%
  summarise(Robberies = sum(Count))%>%
  ggplot(aes(x=FY, y=Robberies, fill = Qrt))+
  geom_bar(stat = 'identity')+
  #scale_fill_manual(values=c('#999999','#E69F00'))+
  geom_text(aes(label=Robberies),  position= position_stack(0.5), size = 2.4)+
  theme_bw()+
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(size = 8),
        axis.title = element_blank())

#Interactive plot
ggplotly(robbery_plot)%>%
  layout(legend = list(
    orientation = "v"))
   

```



