---
title: "Thriving Neighborhoods"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: yeti
    social: ["menu"]
    source_code: "https://github.com/covanalytics/CovData-Dashboards.git"
    self_contained: false
---

<style>                     
.navbar {
  background-color:#46b5d2;
  border-color:black;
}
.navbar-brand {
font-weight: bold;
}

</style> 


```{r eval=TRUE, message=FALSE, warning=FALSE, cache = TRUE}

library(flexdashboard)
library(plyr)
library(tidyverse)
library(lubridate)
library(ggpubr)
library(plotly)
theme_set(theme_pubr())

#Function to abbreviate dollar amounts and add symbol
covdata_comprss <- function(tx) { 
      div <- findInterval(as.numeric(gsub("\\,", "", tx)), 
         c(0, 1e3, 1e6, 1e9, 1e12) )  # modify this if negative numbers are possible
      paste(round( as.numeric(gsub("\\,","",tx))/10^(3*(div-1)), 2), 
           c("","K","M","B","T")[div], sep = "" )}


#//////////////////////////////////////////////////////
## Load All Recycling Account Files from CovData Site /
#//////////////////////////////////////////////////////

##Store recycling accounts file ids in vector
#file for 2018-most current year
#r_file_ids <- c("1-sfLAEJ4GxpPS5y5e0JYeQILcXfWxNgF","1AVEN3ylVdQCeWaCBoZLe61CudPn3N7vU",  "1yONpkXuGjeeety1PGh3kn4i2VTVqCm8T", "1_mf3vC6qu9OLRtcbW4naE_ALTxpk2Oaq", "1CyL-0h0SaE7ecMVGXPKOUvM2q0Hnys8t") 

#Paste file ids and download string and store in list
#dwnld_r_file_ids <- lapply(r_file_ids, function(x) paste("https://drive.google.com/uc?export=download&id=", x, sep = ""))

#Read content of each file into a list
#recycling_files <- lapply(dwnld_r_file_ids, function(x) read.csv(file = x))

#Bind list of files into a data frame
#recycling <- rbind.fill(recycling_files)

load(file = "U:/CityWide Performance/CovStat/CovStat Projects/OpenData/thriving_neighborhoods/recycling.RData")

#Get recycling percentage by month
current_recycling <- recycling %>%
  mutate(Date = ymd(Date))
  #summarise_at(vars(c("NO", "YES", "TOTAL_ACCOUNTS")),  sum, na.rm = TRUE)%>%
  
#Get recent month recycling percentage
month_recycling <- current_recycling %>%
  arrange(desc(Date))%>%
  slice(1)%>%
  mutate(Percent = round(Recycling, 0))
  

#//////////////////////////////////////////////////////
## Load Waste Tonnage /////////////////////////////////
#//////////////////////////////////////////////////////

load(file = "U:/CityWide Performance/CovStat/CovStat Projects/OpenData/thriving_neighborhoods/tonnage.RData", .GlobalEnv)

recycling_profiles <- c("Landfill Diversion", "GREIF RECYCLING", "RIVER METALS")

#remove grouped_df class
tonnage <- as.data.frame(tonnage)

#get current year recycling tonnage
recycling_tonnage <- tonnage %>%
  filter(LandfillDescription %in% recycling_profiles)%>%
  count(FY, wt = ActTons)%>%
  arrange(desc(FY))%>%
  mutate(FY_sort = as.numeric(FY))%>%
  top_n(FY_sort, n = 5)

current_r_tons <- recycling_tonnage%>%
  slice(1)%>%
  select(2)

#//////////////////////////////////////////////////////
## Load Work Orders from Public Works and Solid Waste //
#//////////////////////////////////////////////////////

load(file = "U:/CityWide Performance/CovStat/CovStat Projects/OpenData/thriving_neighborhoods/dpw.RData")

## Pothole Repairs
pothole_repairs <- dpw %>%
  filter(grepl('5001', `Work Type`))%>%
  mutate(FY = as.character(FY))%>%
  count(FY, wt = Orders)%>%
  arrange(desc(FY))%>%
  rename(Orders = n)
  
current_pothole_repairs <- pothole_repairs %>%
  slice(1)%>%
  select(2)


## Cleanups
cleanups <- dpw %>%
  filter(grepl('Cleanup', `Work Type`))%>%
  mutate(FY = as.character(FY))%>%
  count(FY, wt = Orders)%>%
  arrange(desc(FY))%>%
  rename(Orders = n)
  
current_cleanups <- cleanups %>%
  slice(1)%>%
  select(2)

## Waste Receptacle Issues
waste_cans <- dpw %>%
  filter(grepl('300', `Work Type`))%>%
  mutate(FY = as.character(FY))%>%
  count(FY, wt = Orders)%>%
  arrange(desc(FY))%>%
  rename(Orders = n)%>%
  slice(1:3)

current_waste_cans <- waste_cans %>%
  slice(1)%>%
  select(2)

#//////////////////////////////////////////////////////
## Load Code Enforcement Violations  //////////////////
#//////////////////////////////////////////////////////


load(file = "U:/CityWide Performance/CovStat/CovStat Projects/OpenData/thriving_neighborhoods/code_violations.RData")

current_violations <- code_violations %>%
  slice(1) %>%
  select(2)
  


```


Dashboard
===================================


Row
----------------------------------

### Waste Accounts Recycling
```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

valueBox(paste0(month_recycling$Percent, "%", ""),  icon = "fa-recycle", color = "grey")

```

### Waste Tonnage Recycled
```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

valueBox(formatC(current_r_tons, 1000, format = "d", big.mark = ","), icon = "fa-recycle", color = "#46b5d2" )

```


### Potholes Repaired
```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

valueBox(current_pothole_repairs, icon = "fa-road", color = "#D26346" )

```


### Cleanups
```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

valueBox(current_cleanups, icon = "fa-tree", color = "#d246b5" )

```

### Waste Receptacle Issues
```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

valueBox(current_waste_cans, icon = "fa-trash", color = "#46d2a9")

```

### Code Enf. Violations
```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

valueBox(covdata_comprss(current_violations), icon = "fa-building", color = "#b5d246")

```


Row
----------------------------------------------------------------------

### **Recycling Participation %**

```{r eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

#Recycling percentage by month
  recycling_plot <- current_recycling %>%
  mutate(`M-Y` = format(Date, format='%m-%Y'))%>%
  
  ggplot(aes(x=Date, y=Recycling, label = `M-Y`))+
  geom_line(color = "grey") + 
  geom_point(size = 0.6) +
  scale_x_date(date_minor_breaks = "1 month")+
  theme_bw()+
        theme(legend.position = "none",
        legend.title = element_blank(),
        axis.ticks.x = element_line(colour = "black"),
        axis.text = element_text(size = 7), 
        axis.title = element_text(size =9),
        panel.grid.major = element_line(colour = "#D4D2D3"))
  

ggplotly(recycling_plot, tooltip = c("label", "y"))%>%
 plotly::config(displayModeBar = F)%>%
  layout(hoverlabel=list(bgcolor="white"),
         xaxis=list(fixedrange=TRUE), yaxis=list(fixedrange=TRUE))

```

### **Recycling Tonnage**

```{r  eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

#Recycling tonnage by Fiscal Year
  tonnage_plot <- recycling_tonnage %>%
  rename(Tons = n)%>%
  mutate(Tons = round(Tons, 0))%>%
  
  ggplot(aes(x=FY, y=Tons))+
  geom_bar(stat = 'identity', fill = "#46b5d2")+
  ylim(c(0,2800))+
  geom_text(aes(label=paste0(Tons, "<br>")),  position=position_nudge(0.0), size = 3.3)+
  theme_bw()+
  ylab('Tons')+
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(size = 8),
        axis.title = element_blank())

ggplotly(tonnage_plot, tooltip = c("x", "y"))%>%
 config(displayModeBar = F)%>%
  layout(hoverlabel=list(bgcolor="white"),
         hoverinfo = 'none',
         xaxis=list(fixedrange=TRUE), yaxis=list(fixedrange=TRUE))

```

### **Pothole Repairs**

```{r  eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

#Pothole Repairs by Fiscal Year
  pothole_plot <- pothole_repairs %>%
  
  ggplot(aes(x=FY, y=Orders))+
  geom_bar(stat = 'identity', fill = "#D26346")+
  ylim(c(0,500))+
  geom_text(aes(label=paste0(Orders, "<br>")),  position=position_nudge(0.0), size = 3.3)+
  theme_bw()+
  #ylab('orders')+
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(size = 8),
        axis.title = element_blank())

ggplotly(pothole_plot, tooltip = c("x", "y"))%>%
 config(displayModeBar = F)%>%
  layout(hoverlabel=list(bgcolor="white"),
         hoverinfo = 'none',
         xaxis=list(fixedrange=TRUE), yaxis=list(fixedrange=TRUE))

```

Row
----------------------------------------------------------------------
 
### **Cleanups**

```{r  eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

#Cleanups by Fiscal Year
  cleanups_plot <- cleanups %>%
  
  ggplot(aes(x=FY, y=Orders))+
  geom_bar(stat = 'identity', fill = "#d246b5")+
  ylim(c(0,1000))+
  geom_text(aes(label=paste0(Orders, "<br>")),  position=position_nudge(0.0), size = 3.3)+
  theme_bw()+
  #ylab('orders')+
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(size = 8),
        axis.title = element_blank())

ggplotly(cleanups_plot, tooltip = c("x", "y"))%>%
 config(displayModeBar = F)%>%
  layout(hoverlabel=list(bgcolor="white"),
         hoverinfo = 'none',
         xaxis=list(fixedrange=TRUE), yaxis=list(fixedrange=TRUE))

```

### **Waste Receptacle Issues**

```{r  eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

#Waste Receptacle Issues by Fiscal Year
  waste_plot <- waste_cans %>%
  
  ggplot(aes(x=FY, y=Orders))+
  geom_bar(stat = 'identity', fill = "#46d2a9")+
  ylim(c(0,1000))+
  geom_text(aes(label=paste0(Orders, "<br>")),  position=position_nudge(0.0), size = 3.3)+
  theme_bw()+
  #ylab('orders')+
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(size = 8),
        axis.title = element_blank())

ggplotly(waste_plot, tooltip = c("x", "y"))%>%
 config(displayModeBar = F)%>%
  layout(hoverlabel=list(bgcolor="white"),
         hoverinfo = 'none',
         xaxis=list(fixedrange=TRUE), yaxis=list(fixedrange=TRUE))
```

### **Code Enforcement Violations**

```{r  eval = TRUE, echo = FALSE, message = FALSE, warning=FALSE, cache=FALSE}

#Code Enforcement Violations by Fiscal Year
  code_plot <- code_violations %>%
  
  ggplot(aes(x=FY, y=Violations))+
  geom_bar(stat = 'identity', fill = "#b5d246")+
  ylim(c(0,12000))+
  geom_text(aes(label=paste0(Violations, "<br>")),  position=position_nudge(0.0), size = 3.3)+
  theme_bw()+
  #ylab('orders')+
  theme(legend.position = "none",
        legend.title = element_blank(),
        axis.text.x = element_text(size = 8),
        axis.title = element_blank())

ggplotly(code_plot, tooltip = c("x", "y"))%>%
 config(displayModeBar = F)%>%
  layout(hoverlabel=list(bgcolor="white"),
         hoverinfo = 'none',
         xaxis=list(fixedrange=TRUE), yaxis=list(fixedrange=TRUE))
```


Data Info
===================================

Column
-------------------------------------------------------------------
### Data


Column
--------------------------------------------------------------------
